---
title: "Comparing models with resampling"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# 11.1 Creating multiple models with workflow sets

```{r}
basic_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + Latitude + Longitude, data = ames_train) |> 
  step_log(Gr_Liv_Area, base = 10) |> 
  step_other(Neighborhood, threshold = 0.1) |> 
  step_dummy(all_nominal_predictors())

interaction_rec <- 
  basic_rec |> 
  step_interact(~ Gr_Liv_Area:starts_with("Bldg_Type_"))

spline_rec <- 
  interaction_rec |> 
  step_ns(Latitude, Longitude, deg_free = 50)

preproc <- 
  list(basic = basic_rec,
       interact = interaction_rec,
       splines = spline_rec)

lm_models <- workflow_set(preproc, list(lm = linear_reg()), cross = FALSE)

lm_models
```

```{r}
lm_models <- 
  lm_models |> 
  workflow_map("fit_resamples",
               # Options to `workflow_map()`:
               seed = 1001, verbose = TRUE,
               # Options to`fit_resamples()`:
               resamples = ames_folds, control = keep_pred)
lm_models
```

```{r}
collect_metrics(lm_models) |> 
  filter(.metric == "rmse")
```

Add the random forest model:

```{r}
four_models <- 
  as_workflow_set(random_forest = rf_res) |> 
  bind_rows(lm_models)
four_models
```

```{r}
library(ggrepel)
```

```{r}
autoplot(four_models, metric = "rsq") +
  geom_text_repel(aes(label = wflow_id), nudge_x = 1/8, nudge_y = 1/100) +
  theme(legend.position = "none")
```

# 11.2 Comparing resampled performance statistics
